CalorieContent/WebMVC/Controllers/DataRecipeController.cs
using System;
using System.Text;
using CalorieContent.Domain.Mapper;
using CalorieContent.Services.Recipe;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using WebMVC.Models;

namespace WebMVC.Controllers
{
    public class DataRecipeController: Controller
    {
        private readonly IRecipeService _recipeService;

        public DataRecipeController(IRecipeService recipeService)
        {
            _recipeService = recipeService;
        }
        
        public IActionResult Index(int? id)
        {
            return View();
        }

        [HttpPost]
        public ActionResult ShowOne(string? data)
        {
            var result = new ResultViewModel();
            
            if (data == null)
            {
                result.Error = "Введены не валидные данные";
                
                return View("Index", result);
            }
            
            try
            {
                var recipe = _recipeService.GetItem(data);

                var builder = new StringBuilder();
                builder.Append("Название рецепта: " + recipe.Name + "\n");
                builder.Append("Ингредиенты:\n");
                foreach (var ingredient in recipe.Ingredients)
                {
                    builder.Append("\t" + ingredient.Name + " : " +
                                   ingredient.Grams.ToString() + "г\n");
                }
                
                result.Result = builder.ToString();
            }
            catch (Exception e)
            {
                result.Error = e.Message;
            }
            
            return View("Index", result);
        }

        [HttpPost]
        public ActionResult ShowAll()
        {
            var result = new ResultViewModel();

            try
            {
                var recipes = _recipeService.GetAll();

                var builder = new StringBuilder();

                foreach (var recipe in recipes)
                {
                    builder.Append("Название рецепта: " + recipe.Key + "\n");
                    builder.Append("Ингредиенты:\n");
                    foreach (var ingredient in recipe.Value.Ingredients)
                    {
                        builder.Append("\t" + ingredient.Name + " : " +
                                       ingredient.Grams.ToString() + "г\n");
                    }
                }

                result.Result = builder.ToString();
            }
            catch (Exception e)
            {
                result.Error = e.Message;
            }

            return View("Index", result);
        }
        
        [HttpPost] 
        public ActionResult Edit(string? recipeName, string? ingredientsString)
        {
            var result = new ResultViewModel();
            
            if (recipeName == null || ingredientsString == null)
            {
                result.Error = "Введены не валидные данные";
                
                return View("Index", result);
            }

            try
            {
                _recipeService.Set(RecipeMapper.StringToRecipe(recipeName, ingredientsString));

                result.Result = "successful";
            }
            catch (Exception e)
            {
                result.Error = e.Message;
            }

            return View("Index", result);
        }

        [HttpPost]
        public ActionResult Delete(string? recipeName)
        {
            var result = new ResultViewModel();
            
            if (recipeName == null)
            {
                result.Error = "Введены не валидные данные";
                
                return View("Index", result);
            }
            
            try
            {
                var status = _recipeService.Delete(recipeName);
                
                result.Result = status ? "Успешно" : "Не существует записи с введенным именем";
            }
            catch (Exception e)
            {
                result.Error = e.Message;
            }
            return View("Index", result);
        }
        
    }
    
}

CalorieContent/WebMVC/Views/DataRecipe/Index.cshtml
@using CalorieContent.Services.Recipe.Models
@using Microsoft.AspNetCore.Authentication
@{
    ViewData["Title"] = "Работа с БД";
}

<div class="text-center">
    <h1 class="display-4">Рецепты</h1>
    <h2>Работа с данными</h2>

    <div class="wrapper">
        <div class="result">
            <p>1. Отображение одного элемента</p>
            @using (Html.BeginForm("ShowOne", "DataRecipe"))
            {
                <input type="text" name="data" placeholder="название рецепта"/>
                <input type="submit"/>
            }
        </div>

        <div class="result">
            <p>2. Отображение всех записей</p>
            @using (Html.BeginForm("ShowAll", "DataRecipe"))
            {
                <input type="submit"/>
            }
        </div>

        <div class="result">
            <p>3. Редактирование записи</p>
            @using (Html.BeginForm("Edit", "DataRecipe"))
            {
                <input type="text" name="recipeName" placeholder="название рецепта"/>
                <input type="text" name="ingredientsString" placeholder="Ингредиенты"/>
                <input type="submit"/>
                <p>Вводите данные о ингридиентах чере ";" в формате название;сколько_грамм;название;сколько_грамм </p>
            }
        </div>

        <div class="result">
            <p>4. Удаление записи</p>
            @using (Html.BeginForm("Delete", "DataRecipe"))
            {
                <input type="text" name="recipeName" placeholder="название рецепта"/>
                <input type="submit"/>
            }
        </div>

        <div class="result">
            <p>5. Создание записи</p>
            @using (Html.BeginForm("Edit", "DataRecipe"))
            {
                <input type="text" name="recipeName" placeholder="название рецепта"/>
                <input type="text" name="ingredientsString" placeholder="Ингредиенты"/>
                <input type="submit"/>
                <p>Вводите данные о ингридиентах чере ";" в формате название;сколько_грамм;название;сколько_грамм </p>
            }
        </div>


        <div class="result">
            @model ResultViewModel
            @if (Model != null)
            {
                if (!string.IsNullOrEmpty(Model.Error))
                {
                    <p>Работы метода завершилась с ошибкой</p>
                    <pre>@Model.Error</pre>
                }
                else
                {
                    <p>Результат работы метода</p>
                    <pre>@Model.Result</pre>
                }
            }
        </div>

    </div>
    <div>
       
    </div>
</div>